name: Update Appwrite
on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"   # removes leading 'v'
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "Extracted version: $VERSION"

      - name: Appwrite action
        uses: appwrite/setup-for-appwrite@v1
        with:
          method: key
          key: ${{ secrets.APPWRITE_API_TOKEN }}
          project: ${{ secrets.APPWRITE_PROJECT_ID }}
          self_signed: false
      
      - name: Update Table Row
        id: update_table_row
        run: |
          appwrite tables-db update-row \
            --database-id "${{ secrets.APPWRITE_DATABASE_ID }}" \
            --table-id "${{ secrets.APPWRITE_TABLE_ID }}" \
            --row-id '68b585c20021dffba015' \
            --data "{\"version\":\"${{ env.VERSION }}\"}"

            
