name: Update Appwrite
on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    env: 
      APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
      APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
      APPWRITE_API_TOKEN: ${{ secrets.APPWRITE_API_TOKEN }}
      APPWRITE_DATABASE_ID: ${{ secrets.APPWRITE_DATABASE_ID }}
      APPWRITE_TABLE_ID: ${{ secrets.APPWRITE_TABLE_ID }}
      TEBI_ACCESS_ID: ${{ secrets.TEBI_ACCESS_ID }}
      TEBI_ACCESS_KEY: ${{ secrets.TEBI_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2

      - name: Install dependencies
        run: bun install
      
      - name: Update Table Row
        id: update_table_row
        run: bun run main

            
