name: Update Appwrite
on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    env: 
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SECRET_KEYS: ${{ secrets.SUPABASE_SECRET_KEYS }}
      TEBI_ACCESS_ID: ${{ secrets.TEBI_ACCESS_ID }}
      TEBI_ACCESS_KEY: ${{ secrets.TEBI_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2

      - name: Install dependencies
        run: bun install
      
      - name: Update Database
        run: bun run main

            
