name: Update Appwrite
on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    env: 
      APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
      APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
      APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_TOKEN }}
      APPWRITE_DATABASE_ID: ${{ secrets.APPWRITE_DATABASE_ID }}
      APPWRITE_TABLE_ID: ${{ secrets.APPWRITE_TABLE_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"   # removes leading 'v'
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "Extracted version: $VERSION"

      - name: Install Appwrite
        run: |
          curl -sL https://appwrite.io/cli/install.sh | bash
          appwrite -v
      
      - name: Setup Appwrite
        run: |
          appwrite client \
          --endpoint $APPWRITE_ENDPOINT \
          --project-id $APPWRITE_PROJECT_ID \
          --key $APPWRITE_API_KEY

      
      - name: Update Table Row
        id: update_table_row
        run: |
          appwrite tables-db update-row \
            --database-id "$APPWRITE_DATABASE_ID" \
            --table-id "$APPWRITE_TABLE_ID" \
            --row-id '68b585c20021dffba015' \
            --data "{\"version\":\"${{ env.VERSION }}\"}"

            
